add_newline = false
command_timeout = 200
format = "[$directory$git_branch$git_status]($style)$character"

[directory]
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
style      = "cyan"
